name: Link Checker 

on:
  workflow_dispatch: 
    inputs:
      deployment:
        description: 'Select the deployment to check links in'
        required: true
        default: 'ballerina.io'
        type: choice
        options:
        - ballerina.io
        - pre-prod.ballerina.io
        - lib.ballerina.io
        - staging-lib.ballerina.io
        - dev-lib.ballerina.io
        - blog.ballerina.io

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node
      uses: actions/setup-node@v3
    - name: Run link checker
      env:
        DEPLOYMENT: ${{ inputs.deployment }}
      run: |
        npm install --global @deptagency/octopus@latest
        
        URL=https://$DEPLOYMENT/
        echo "Checking links in $URL"

        # Run octopus and catch errors for better logging
        set -e
        {
          octopus $URL
        } || {
          echo "Error occurred while running octopus"
          echo "Debugging info: URL=$URL, Deployment=$DEPLOYMENT"
          exit 1
        }
